# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailtrail', '0002_auto_20170218_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='backend',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
